import type { ListedWeightTerm, TruckLeadInput, SupplierContactInput } from "@/types/sourcing";
import {
  buildSourceListingId,
  buildSourceScope,
  canonicalizeListingUrl,
} from "@/lib/sourcing/duplicates";

/**
 * Unverified seed research from the Sept 18, 2026 SKL Box Truck Sourcing Report.
 * Category-page auction entries (e.g. Purple Wave inventory listings) are NOT imported
 * as individual trucks. Individual listing URLs and uncertainty labels are preserved.
 */
export const SEED_REPORT_LABEL = "SKL Box Truck Sourcing Report — Sept 18, 2026 (unverified seed)";

type SeedLead = Omit<TruckLeadInput, "supplierContactId"> & {
  seedKey: string;
  supplierCompany?: string;
};

export const SEED_SUPPLIER_CONTACTS: (SupplierContactInput & { seedKey: string })[] = [
  {
    seedKey: "debary",
    company: "DeBary Truck Sales",
    contactName: "",
    role: "Sales team",
    phone: "(407) 321-4244",
    email: "",
    sourceUrl: "https://www.debarytrucksales.com/contact-us",
    supplierType: "Independent dealer",
    dealerWholesaleStatus: "Worth asking — dealer pricing / advance notice",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 1080,
    phoneVerified: true,
    researchNotes:
      "Verified on official site Sept 18, 2026. Text also listed: 407-212-6120. Unverified seed research.",
  },
  {
    seedKey: "miller",
    company: "Miller Used Trucks / Miller Truck Leasing",
    contactName: "",
    role: "Sales team",
    phone: "(856) 214-3660",
    email: "",
    sourceUrl: "https://www.millerusedtrucks.com/",
    supplierType: "Dealer + fleet leasing",
    dealerWholesaleStatus: "Worth asking — off-lease advance notice",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 1183,
    phoneVerified: true,
    researchNotes:
      "Lumberton NJ number verified on official site. Brockton MA (508) 861-6510 carried forward — confirm on call.",
  },
  {
    seedKey: "country",
    company: "Country Truck Sales",
    contactName: "",
    role: "Sales team",
    phone: "(419) 394-7178",
    email: "",
    sourceUrl: "https://countrytrucksales.com/",
    supplierType: "Dealer",
    dealerWholesaleStatus: "Worth asking",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 703,
    phoneVerified: true,
    researchNotes: "Phone verified on official site Sept 18, 2026. Ohio area.",
  },
  {
    seedKey: "purple-wave",
    company: "Purple Wave Auction",
    contactName: "",
    role: "Registration required to bid",
    phone: "",
    email: "",
    sourceUrl:
      "https://www.purplewave.com/inventory/commercial-trucks-medium-heavy-duty/trucks/box-truck/freightliner/for-sale",
    supplierType: "No-reserve auction platform",
    dealerWholesaleStatus: "Open to public; no dealer license required",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes:
      "Monitor category daily. Do not treat category-page auction rows as verified individual trucks. Unverified seed.",
  },
  {
    seedKey: "penske",
    company: "Penske Used Trucks",
    contactName: "",
    role: "Fleet and Dealer Sales",
    phone: "866-309-1962",
    email: "",
    sourceUrl: "https://www.penskeusedtrucks.com/contact-penske/",
    supplierType: "Fleet owner + used truck seller",
    dealerWholesaleStatus: "Worth asking — advance notice",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call. Unverified seed.",
  },
  {
    seedKey: "ryder",
    company: "Ryder Used Trucks",
    contactName: "",
    role: "Used Truck Sales",
    phone: "855-643-7072",
    email: "",
    sourceUrl: "https://www.ryder.com/en-us/used-trucks",
    supplierType: "Fleet owner + used truck seller",
    dealerWholesaleStatus: "Worth asking",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call. Unverified seed.",
  },
  {
    seedKey: "nationalease",
    company: "NationaLease",
    contactName: "",
    role: "Remarketing team",
    phone: "866-813-1900",
    email: "",
    sourceUrl: "https://www.nationalease.com/used-trucks/",
    supplierType: "Network of leasing businesses",
    dealerWholesaleStatus: "Worth asking — member remarketing",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "fleet-advantage",
    company: "Fleet Advantage",
    contactName: "",
    role: "Remarketing Sales",
    phone: "954-615-4400",
    email: "",
    sourceUrl: "https://www.fleetadvantage.com/contact",
    supplierType: "Fleet leasing + remarketing",
    dealerWholesaleStatus: "Worth asking — advance notice before auction",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 1100,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "merchants",
    company: "Merchants Fleet",
    contactName: "",
    role: "Merchants Commercial Sales",
    phone: "888-846-2986",
    email: "",
    sourceUrl: "https://www.merchantsfleet.com/commercial-business-fleet-program/",
    supplierType: "Fleet leasing + Dealer Direct",
    dealerWholesaleStatus: "Worth asking — Dealer Direct alerts",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "holman",
    company: "Holman Vehicle Remarketing",
    contactName: "Brian McBrearty",
    role: "Contact (prior report)",
    phone: "856-778-6381",
    email: "",
    sourceUrl: "https://vr.holman.com/Equipment/Home/Contact",
    supplierType: "Fleet management + remarketing",
    dealerWholesaleStatus: "Worth asking — BuyDirect dealer portal",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 1183,
    phoneVerified: false,
    researchNotes:
      "Named contact carried forward from prior report — could not be independently re-verified Sept 18, 2026.",
  },
  {
    seedKey: "enterprise",
    company: "Enterprise Truck Sales",
    contactName: "",
    role: "Enterprise Truck Sales",
    phone: "877-487-5725",
    email: "",
    sourceUrl: "https://www.enterprisetrucks.com/",
    supplierType: "Fleet owner + used truck seller",
    dealerWholesaleStatus: "Worth asking — Direct Dealer Program",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "paclease",
    company: "PacLease (PACCAR Financial)",
    contactName: "",
    role: "Used Truck Sales",
    phone: "844-556-6243",
    email: "",
    sourceUrl: "https://www.paclease.com/our-trucks/used-equipment/",
    supplierType: "PACCAR leasing arm",
    dealerWholesaleStatus: "Worth asking",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "fleet-rms",
    company: "Fleet Remarketing Services",
    contactName: "Terry Dietrich / Michelle Boyd",
    role: "Wholesale (prior report)",
    phone: "877-228-3914",
    email: "",
    sourceUrl: "https://www.fleetrms.com/",
    supplierType: "Wholesale dealer",
    dealerWholesaleStatus: "Worth asking — dealer network",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes:
      "Named contacts (ext. 309 / 312) carried forward — could not be independently re-verified.",
  },
  {
    seedKey: "rush",
    company: "Rush Truck Centers",
    contactName: "",
    role: "Ready to Roll Sales",
    phone: "855-765-7874",
    email: "",
    sourceUrl: "https://www.rushtruckcenters.com/",
    supplierType: "OEM dealer network",
    dealerWholesaleStatus: "Worth asking — trade-in pipeline",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: null,
    phoneVerified: false,
    researchNotes: "General switchboard carried forward — confirm on call.",
  },
  {
    seedKey: "drs",
    company: "DRS Trucks",
    contactName: "",
    role: "Sales",
    phone: "",
    email: "",
    sourceUrl: "https://inventory.drstrucks.com/",
    supplierType: "Dealer",
    dealerWholesaleStatus: "Unknown",
    lastContactDate: null,
    nextFollowUpDate: null,
    callNotes: "",
    drivingDistanceMiles: 703,
    phoneVerified: false,
    researchNotes: "From seed report near-match listing. Confirm contact details on call.",
  },
];

function leadBase(
  partial: Partial<SeedLead> &
    Pick<
      SeedLead,
      | "seedKey"
      | "seller"
      | "sourceUrl"
      | "stockNumber"
      | "year"
      | "makeModel"
      | "verificationNotes"
    >
): SeedLead {
  const canonical = canonicalizeListingUrl(partial.canonicalListingUrl || partial.sourceUrl);
  const sourceScope = buildSourceScope({
    seller: partial.seller,
    sourceUrl: partial.sourceUrl,
    sourceScope: partial.sourceScope,
  });
  const sourceListingId = buildSourceListingId({
    sourceListingId: partial.sourceListingId || partial.seedKey,
    stockNumber: partial.stockNumber,
  });

  return {
    seller: partial.seller,
    sourceUrl: partial.sourceUrl,
    sourceScope,
    sourceListingId,
    canonicalListingUrl: canonical,
    stockNumber: partial.stockNumber ?? "",
    vin: partial.vin ?? "",
    year: partial.year ?? null,
    makeModel: partial.makeModel,
    boxLengthFt: partial.boxLengthFt ?? null,
    boxLengthRaw: partial.boxLengthRaw ?? "",
    engine: partial.engine ?? "",
    engineIsCummins: partial.engineIsCummins ?? null,
    transmission: partial.transmission ?? "",
    transmissionIsAutomatic: partial.transmissionIsAutomatic ?? null,
    listedWeightLbs: partial.listedWeightLbs ?? null,
    listedWeightTerm: (partial.listedWeightTerm ?? "unknown") as ListedWeightTerm,
    manufacturerGvwrLbs: partial.manufacturerGvwrLbs ?? null,
    gvwrDoorPlateVerified: partial.gvwrDoorPlateVerified ?? false,
    mileage: partial.mileage ?? null,
    hasLiftgate: partial.hasLiftgate ?? null,
    liftgateNotes: partial.liftgateNotes ?? "",
    price: partial.price ?? null,
    location: partial.location ?? "",
    drivingDistanceMiles: partial.drivingDistanceMiles ?? null,
    distanceIsEstimate: partial.distanceIsEstimate ?? true,
    dateLastChecked: partial.dateLastChecked ?? "2026-09-18",
    verificationNotes: partial.verificationNotes,
    workflowStatus: partial.workflowStatus ?? "new",
    sklCallNotes: partial.sklCallNotes ?? "",
    researchUncertaintyLabels: partial.researchUncertaintyLabels ?? ["unverified_seed_research"],
    isSeedResearch: true,
    seedSource: SEED_REPORT_LABEL,
    seedKey: partial.seedKey,
    supplierCompany: partial.supplierCompany,
  };
}

/** Individual-listing candidates only — no Purple Wave category auction rows. */
export const SEED_TRUCK_LEADS: SeedLead[] = [
  // Part 2 — strongest candidates (GVW, not GVWR)
  leadBase({
    seedKey: "debary-7908",
    seller: "DeBary Truck Sales",
    supplierCompany: "DeBary Truck Sales",
    sourceUrl:
      "https://www.debarytrucksales.com/inventory/used-2017-freightliner-m2-106-3alacwdt1hdhv6031-in-sanford-fl",
    stockNumber: "7908",
    vin: "3ALACWDT1HDHV6031",
    year: 2017,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 24,
    boxLengthRaw: "24'",
    engine: "6.7L Cummins Turbo Diesel",
    engineIsCummins: true,
    transmission: "Allison Automatic",
    transmissionIsAutomatic: true,
    listedWeightLbs: 25999,
    listedWeightTerm: "gvw",
    mileage: 160000,
    hasLiftgate: true,
    liftgateNotes: "Maxon GPT, 3,500 lb capacity (stated on listing)",
    price: 33900,
    location: "Sanford, FL",
    drivingDistanceMiles: 1080,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "gvw_not_gvwr",
      "distance_estimate",
    ],
    verificationNotes:
      'Listing uses "GVW" 25,999 — not manufacturer-rated GVWR. Request door-plate confirmation before purchase.',
  }),
  leadBase({
    seedKey: "debary-7911",
    seller: "DeBary Truck Sales",
    supplierCompany: "DeBary Truck Sales",
    sourceUrl:
      "https://www.debarytrucksales.com/inventory/used-2019-freightliner-m2-106-3alacwfc3kdkt3952-in-sanford-fl",
    stockNumber: "7911",
    vin: "3ALACWFC3KDKT3952",
    year: 2019,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "6.7L Cummins Turbo Diesel",
    engineIsCummins: true,
    transmission: "Automatic (make/model not stated)",
    transmissionIsAutomatic: true,
    listedWeightLbs: 25999,
    listedWeightTerm: "gvw",
    mileage: 146000,
    hasLiftgate: true,
    liftgateNotes: "Maxon GPT (capacity not stated)",
    price: 45900,
    location: "Sanford, FL",
    drivingDistanceMiles: 1080,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "gvw_not_gvwr",
      "transmission_make_unstated",
      "distance_estimate",
    ],
    verificationNotes:
      'Listing uses "GVW" 25,999 — request door-plate GVWR. Transmission make/model not stated.',
  }),
  leadBase({
    seedKey: "miller-383541",
    seller: "Miller Used Trucks / Miller Truck Leasing",
    supplierCompany: "Miller Used Trucks / Miller Truck Leasing",
    sourceUrl: "https://www.millerusedtrucks.com/trucks/box-van-truck/freightliner/m2106/5743/",
    stockNumber: "383541",
    vin: "3ALACWFC7JDJY3541",
    year: 2018,
    makeModel: "Freightliner M2106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "Cummins ISB 6.7L (specs say 260 HP; description says 220 HP)",
    engineIsCummins: true,
    transmission: "Allison Auto 2100, 6 SPD",
    transmissionIsAutomatic: true,
    listedWeightLbs: 25500,
    listedWeightTerm: "gvw",
    mileage: 159417,
    hasLiftgate: true,
    liftgateNotes: "Maxon 60 (capacity not stated)",
    price: 39990,
    location: "Lumberton, NJ",
    drivingDistanceMiles: 1183,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "gvw_not_gvwr",
      "horsepower_discrepancy",
      "distance_borderline_estimate",
    ],
    verificationNotes:
      'Listing uses "GVW" 25,500 — request door-plate GVWR. Resolve 260 vs 220 HP discrepancy. Distance ~1,183 mi is borderline at 1,200 preferred limit.',
  }),
  // Part 3 — aggregator; seller unidentified; source is not a seller individual page
  leadBase({
    seedKey: "machinio-2666-orlando",
    seller: "Not identified (Machinio aggregator)",
    sourceUrl: "https://www.machinio.com/freightliner/box-straight-trucks/florida",
    // Keep seed key as listing id — category URL is NOT treated as a verified individual listing
    sourceListingId: "machinio-stock-2666-orlando-unverified",
    canonicalListingUrl: "",
    stockNumber: "2666",
    year: 2019,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "Cummins B6.7L 220HP",
    engineIsCummins: true,
    transmission: "Automatic",
    transmissionIsAutomatic: true,
    listedWeightLbs: 25999,
    listedWeightTerm: "gvw",
    mileage: 200361,
    hasLiftgate: true,
    liftgateNotes: "Liftgate & Ramp (aggregator page)",
    price: 34900,
    location: "Orlando, FL",
    drivingDistanceMiles: 1076,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "aggregator_only",
      "seller_unidentified",
      "no_seller_individual_listing_page",
      "gvw_not_gvwr",
      "category_or_aggregator_url",
    ],
    verificationNotes:
      "Found on Machinio aggregator only — seller not identified; no individual seller listing page. Do not treat as verified. Identify seller and verify all specs before considering.",
  }),
  // Part 4 — confirmed near-match failures with individual listing URLs (skip Purple Wave category auctions)
  leadBase({
    seedKey: "debary-7903",
    seller: "DeBary Truck Sales",
    supplierCompany: "DeBary Truck Sales",
    sourceUrl:
      "https://www.debarytrucksales.com/inventory/used-2020-freightliner-m2-106-3alacwfc3ldlv8306-in-sanford-fl",
    stockNumber: "7903",
    vin: "3ALACWFC3LDLV8306",
    year: 2020,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "Cummins Turbo Diesel 6.7L, 250 HP",
    engineIsCummins: true,
    transmission: "Allison Automatic",
    transmissionIsAutomatic: true,
    listedWeightLbs: 26000,
    listedWeightTerm: "gvw",
    mileage: 270000,
    hasLiftgate: true,
    liftgateNotes: "Maxon tuckaway",
    price: 36850,
    location: "Sanford, FL",
    drivingDistanceMiles: 1080,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "gvw_not_gvwr",
      "weight_discrepancy_youtube_vs_listing",
    ],
    verificationNotes:
      "Current listing weight field is 26,000 GVW (YouTube said 25,999). Does not evidence sub-26,000 manufacturer GVWR. Unverified seed.",
  }),
  leadBase({
    seedKey: "drs-593",
    seller: "DRS Trucks",
    supplierCompany: "DRS Trucks",
    sourceUrl:
      "https://inventory.drstrucks.com/trucks/?vid=1152&unit=2019-freightliner-business-class-m2-106",
    stockNumber: "593",
    year: 2019,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "Cummins",
    engineIsCummins: true,
    transmission: "Auto",
    transmissionIsAutomatic: true,
    listedWeightLbs: 26000,
    listedWeightTerm: "other",
    mileage: 175000,
    hasLiftgate: true,
    price: 38900,
    location: "OH area",
    drivingDistanceMiles: 703,
    researchUncertaintyLabels: ["unverified_seed_research", "weight_field_26000"],
    verificationNotes: "Listing weight field is 26,000 — fails strictly-below-26,000 GVWR profile.",
  }),
  // Part 5 — needs verification, individual URLs
  leadBase({
    seedKey: "country-4421",
    seller: "Country Truck Sales",
    supplierCompany: "Country Truck Sales",
    sourceUrl: "https://countrytrucksales.com/inventory/specsheet_res/?ID=16422506",
    stockNumber: "4421",
    year: 2020,
    makeModel: "Freightliner M2 106",
    boxLengthFt: null,
    boxLengthRaw: "Not stated",
    engine: "Cummins 220 ISB",
    engineIsCummins: true,
    transmission: "Allison 2200RDS",
    transmissionIsAutomatic: true,
    listedWeightLbs: null,
    listedWeightTerm: "unknown",
    mileage: 141393,
    hasLiftgate: null,
    price: 48900,
    location: "OH area",
    drivingDistanceMiles: 703,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "gvwr_not_stated",
      "box_length_not_stated",
      "liftgate_not_stated",
    ],
    verificationNotes:
      "GVWR, box length, and liftgate not stated — call to verify before considering.",
  }),
  leadBase({
    seedKey: "ryder-soarr-2019-28",
    seller: "Ryder Vehicle Sales (via SOARR)",
    supplierCompany: "Ryder Used Trucks",
    sourceUrl: "https://www.soarr.com/for-sale/trucks/10/Freightliner/M2/box-trucks-for-sale-in-florida",
    sourceListingId: "soarr-ryder-2019-m2-28-orlando",
    canonicalListingUrl: "",
    stockNumber: "",
    year: 2019,
    makeModel: "Freightliner M2",
    boxLengthFt: 28,
    boxLengthRaw: "28'",
    engine: "Cummins 300",
    engineIsCummins: true,
    transmission: "6 Speed",
    transmissionIsAutomatic: null,
    listedWeightLbs: null,
    listedWeightTerm: "unknown",
    mileage: 255305,
    hasLiftgate: null,
    price: 59995,
    location: "Orlando, FL",
    drivingDistanceMiles: 1076,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "aggregator_listing",
      "gvwr_not_stated",
      "transmission_automatic_unconfirmed",
      "liftgate_not_stated",
    ],
    verificationNotes:
      "Third-party SOARR listing — confirm on Ryder, verify GVWR and whether 6 Speed is automatic. Phone 855-785-9873 carried forward.",
  }),
  // Out-of-range with enough individual identity (not inventing distance)
  leadBase({
    seedKey: "tvo-lw9088",
    seller: "Truck and Van Outlet",
    sourceUrl: "",
    sourceListingId: "tvo-lw9088",
    stockNumber: "LW9088",
    year: 2020,
    makeModel: "Freightliner M2 106",
    boxLengthFt: 26,
    boxLengthRaw: "26'",
    engine: "Cummins B6.7, 200HP",
    engineIsCummins: true,
    transmission: "Allison RDS Automatic",
    transmissionIsAutomatic: true,
    listedWeightLbs: null,
    listedWeightTerm: "unknown",
    mileage: null,
    hasLiftgate: null,
    price: null,
    location: "Miami, FL",
    drivingDistanceMiles: 1392,
    researchUncertaintyLabels: [
      "unverified_seed_research",
      "out_of_preferred_range",
      "gvwr_not_stated",
      "no_individual_url_in_report",
    ],
    verificationNotes:
      "Outside preferred 1,200 driving miles (~1,392). GVWR not stated. Seed from report Part 5 removed candidates — no individual URL captured in report.",
  }),
];

export { type SeedLead };
