import type { LeadComparisonSnapshot } from "@/lib/sourcing/market-comparison/types";
import type { ComparableListingRaw } from "@/lib/sourcing/market-comparison/types";
import type { SearchApiUsage } from "@/lib/sourcing/search/types";

/** Deterministic mock listings for unit tests and unpaid dry runs — not live web results. */
export function mockComparableListings(lead: LeadComparisonSnapshot): ComparableListingRaw[] {
  const year = lead.year ?? 2019;
  const miles = lead.mileage ?? 140000;
  const box = lead.boxLengthFt ?? 26;
  const model = lead.makeModel || "Freightliner M2";

  return [
    {
      listingUrl: "https://www.commercialtrucktrader.com/listing/2019-freightliner-m2-26ft-mock-1001",
      sourceName: "Commercial Truck Trader",
      year,
      makeModel: model,
      mileage: miles - 12000,
      askingPrice: (lead.price ?? 42000) + 4500,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "dry van box",
      engine: "Cummins ISB 6.7",
      engineIsCummins: true,
      transmission: "Allison automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: true,
      location: "Springfield, MO",
      conditionNotes: "",
      statusNotes: "For sale",
      evidenceNotes: "Mock individual listing with asking price.",
    },
    {
      listingUrl: "https://www.example-dealer.com/inventory/used-2018-freightliner-m2-mock-1002",
      sourceName: "TruckPaper (mirrored mock dealer URL)",
      year: year - 1,
      makeModel: model,
      mileage: miles + 8000,
      askingPrice: (lead.price ?? 42000) + 2000,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "box truck",
      engine: "Cummins",
      engineIsCummins: true,
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 26000,
      hasLiftgate: lead.hasLiftgate ?? true,
      location: "Tulsa, OK",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Mock individual unit page (TruckPaper-style source label).",
    },
    {
      listingUrl: "https://www.debarytrucksales.com/inventory/used-2018-freightliner-m2-mock-1003",
      sourceName: "Dealer inventory",
      year: year - 1,
      makeModel: model,
      mileage: miles + 22000,
      askingPrice: (lead.price ?? 42000) + 6000,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "26 ft dry van",
      engine: "Cummins ISB",
      engineIsCummins: true,
      transmission: "Allison",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25999,
      hasLiftgate: true,
      location: "Sanford, FL",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Mock dealer inventory page.",
    },
    {
      listingUrl: "https://www.soarr.com/inventory/freightliner-m2-26-mock-1004",
      sourceName: "SOARR",
      year: year + 1,
      makeModel: model,
      mileage: miles - 30000,
      askingPrice: (lead.price ?? 42000) + 9000,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "dry van",
      engine: "Cummins",
      engineIsCummins: true,
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: true,
      location: "Kansas City, MO",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Mock SOARR listing.",
    },
    {
      listingUrl: "https://www.millerusedtrucks.com/inventory/used-freightliner-m2-mock-1005",
      sourceName: "Dealer inventory",
      year,
      makeModel: model,
      mileage: miles + 5000,
      askingPrice: (lead.price ?? 42000) + 3500,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "box",
      engine: "Cummins ISB 6.7",
      engineIsCummins: true,
      transmission: "Allison automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: false,
      location: "Lumberton, NJ",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Mock dealer listing.",
    },
    // Exclusions mixed in — must not fail the run
    {
      listingUrl: "https://www.commercialtrucktrader.com/box-trucks-for-sale",
      sourceName: "Commercial Truck Trader",
      year,
      makeModel: model,
      mileage: miles,
      askingPrice: 50000,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "box truck",
      engine: "Cummins",
      engineIsCummins: true,
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: true,
      location: "Online",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Category hub — should exclude.",
    },
    {
      listingUrl: "https://www.example-dealer.com/inventory/used-reefer-mock-1006",
      sourceName: "Dealer inventory",
      year,
      makeModel: model,
      mileage: miles,
      askingPrice: 48000,
      auctionCurrentBid: null,
      boxLengthFt: box,
      bodyType: "reefer",
      engine: "Cummins",
      engineIsCummins: true,
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: true,
      location: "Dallas, TX",
      conditionNotes: "",
      statusNotes: "",
      evidenceNotes: "Reefer body — exclude.",
    },
    {
      listingUrl: "https://www.example-dealer.com/inventory/auction-unit-mock-1007",
      sourceName: "Auction listing",
      year,
      makeModel: model,
      mileage: miles,
      askingPrice: null,
      auctionCurrentBid: 31000,
      boxLengthFt: box,
      bodyType: "dry van",
      engine: "Cummins",
      engineIsCummins: true,
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      manufacturerGvwrLbs: 25500,
      hasLiftgate: true,
      location: "Chicago, IL",
      conditionNotes: "",
      statusNotes: "Auction current bid",
      evidenceNotes: "Auction without asking — exclude.",
    },
  ];
}

export function mockMarketComparisonUsage(): SearchApiUsage {
  return {
    provider: "mock",
    model: "mock",
    webSearchCalls: 0,
    inputTokens: 0,
    outputTokens: 0,
    estimatedCostUsd: 0,
    live: false,
    creditsConsumed: 0,
    searchesRun: 0,
    extractsRun: 0,
  };
}
