import type { SearchApiUsage, SearchModelPayload } from "@/lib/sourcing/search/types";

/**
 * Deterministic mock for automated tests and dry runs without live API keys.
 * Mimics individual listings + seller phones (not category search links).
 */
export const MOCK_SEARCH_PAYLOAD: SearchModelPayload = {
  queriesUsed: [],
  sourcesConsulted: [
    "www.debarytrucksales.com",
    "www.penskeusedtrucks.com",
    "www.millerusedtrucks.com",
  ],
  notes: "Mock payload for nonprod pilot tests — not live web results.",
  trucks: [
    {
      listingUrl:
        "https://www.debarytrucksales.com/inventory/used-2019-freightliner-m2-106-mock-intake-9001",
      sourceName: "DeBary Truck Sales",
      seller: "DeBary Truck Sales",
      stockNumber: "MOCK-9001",
      vin: "3ALACWDT0KDHV9001",
      year: 2019,
      makeModel: "Freightliner M2 106",
      engine: "Cummins ISB 6.7",
      engineIsCummins: true,
      engineEvidence: "Listing engine line: Cummins ISB 6.7",
      transmission: "Allison automatic",
      transmissionIsAutomatic: true,
      transmissionEvidence: "Listing transmission: Allison automatic",
      boxLengthFt: 26,
      boxLengthEvidence: "Listing body: 26 ft dry van",
      manufacturerGvwrLbs: 25500,
      listedWeightLbs: 25500,
      listedWeightTerm: "gvwr",
      gvwrEvidence: "Listing states manufacturer-rated GVWR 25,500 lbs",
      mileage: 142000,
      hasLiftgate: true,
      askingPrice: 42900,
      auctionCurrentBid: null,
      location: "Sanford, FL",
      drivingDistanceMiles: 1080,
      distanceIsEstimate: true,
      phone: "(407) 321-4244",
      contactName: "",
      contactRole: "Sales",
      evidenceUrl:
        "https://www.debarytrucksales.com/inventory/used-2019-freightliner-m2-106-mock-intake-9001",
      notes: "Mock individual listing with full evidence.",
    },
    {
      listingUrl:
        "https://www.millerusedtrucks.com/inventory/used-2018-freightliner-m2-mock-383999",
      sourceName: "Miller Used Trucks",
      seller: "Miller Used Trucks",
      stockNumber: "MOCK-383999",
      vin: "",
      year: 2018,
      makeModel: "Freightliner M2",
      engine: "Cummins",
      engineIsCummins: true,
      engineEvidence: "",
      transmission: "Automatic",
      transmissionIsAutomatic: true,
      transmissionEvidence: "",
      boxLengthFt: 26,
      boxLengthEvidence: "",
      manufacturerGvwrLbs: null,
      listedWeightLbs: 26000,
      listedWeightTerm: "gvw",
      gvwrEvidence: "",
      mileage: 168000,
      hasLiftgate: true,
      askingPrice: 39900,
      auctionCurrentBid: null,
      location: "Lumberton, NJ",
      drivingDistanceMiles: 1180,
      distanceIsEstimate: true,
      phone: "(609) 555-0142",
      contactName: "",
      contactRole: "",
      evidenceUrl:
        "https://www.millerusedtrucks.com/inventory/used-2018-freightliner-m2-mock-383999",
      notes: "Mock listing missing required evidence — should Needs verification.",
    },
    {
      listingUrl: "https://www.penskeusedtrucks.com/search-inventory/",
      sourceName: "Penske Used Trucks",
      seller: "Penske Used Trucks",
      stockNumber: "",
      vin: "",
      year: null,
      makeModel: "",
      engine: "",
      engineIsCummins: null,
      engineEvidence: "",
      transmission: "",
      transmissionIsAutomatic: null,
      transmissionEvidence: "",
      boxLengthFt: null,
      boxLengthEvidence: "",
      manufacturerGvwrLbs: null,
      listedWeightLbs: null,
      listedWeightTerm: "unknown",
      gvwrEvidence: "",
      mileage: null,
      hasLiftgate: null,
      askingPrice: null,
      auctionCurrentBid: null,
      location: "",
      drivingDistanceMiles: null,
      distanceIsEstimate: true,
      phone: "",
      contactName: "",
      contactRole: "",
      evidenceUrl: "https://www.penskeusedtrucks.com/search-inventory/",
      notes: "Category search page — must be rejected.",
    },
  ],
  contacts: [
    {
      company: "DeBary Truck Sales",
      contactName: "",
      role: "Sales team",
      phone: "(407) 321-4244",
      email: "",
      sourceUrl: "https://www.debarytrucksales.com/contact-us",
      supplierType: "Independent dealer",
      evidenceQuote: "Contact page lists (407) 321-4244",
      notes: "Mock publicly verified dealer phone.",
    },
    {
      company: "Invented Fleet Co",
      contactName: "John Doe",
      role: "Sales",
      phone: "",
      email: "",
      sourceUrl: "https://example.com",
      supplierType: "Fleet",
      evidenceQuote: "",
      notes: "No phone — reject.",
    },
  ],
};

export const MOCK_SEARCH_USAGE: SearchApiUsage = {
  provider: "mock",
  model: "mock",
  webSearchCalls: 0,
  inputTokens: 0,
  outputTokens: 0,
  estimatedCostUsd: 0,
  live: false,
  creditsConsumed: 0,
  searchesRun: 0,
  extractsRun: 0,
};

/** Fixture shaped like Tavily search + extract responses (no network). */
export const MOCK_TAVILY_SEARCH_PAGES = [
  {
    url: "https://www.debarytrucksales.com/inventory/used-2019-freightliner-m2-106-mock-intake-9001",
    title: "2019 Freightliner M2 106 26 ft Box Truck",
    content:
      "Stock MOCK-9001. Cummins ISB 6.7 diesel. Allison automatic transmission. 26 ft dry van with liftgate. Manufacturer-rated GVWR 25,500 lbs. 142,000 miles. Asking price $42,900. Sanford, FL. Call (407) 321-4244. VIN 3ALACWDT0KDHV9001.",
  },
  {
    url: "https://www.penskeusedtrucks.com/search-inventory/",
    title: "Search inventory",
    content: "Browse Penske used trucks.",
  },
  {
    url: "https://www.millerusedtrucks.com/inventory/used-2018-freightliner-m2-mock-383999",
    title: "2018 Freightliner M2",
    content:
      "Cummins engine, automatic, 26 ft box, GVW 26,000 lbs, 168,000 miles, $39,900, Lumberton, NJ. Phone (609) 555-0142.",
  },
];
